### ISSUE TITLE
UR vs UB umi tag

### ISSUE THREAD

**Issue by christinedien** [MonashBioinformaticsPlatform/polyApipe#2]
Hello!

Thank you for the tool. I got the following error because my BAM files are missing the `UR` tag:
```
"Fix by annotating cell barcodes and/or UMIs in tags in bam file, and specifying the tags with"+
        " (--cell_barcode_tag / --umi_tag)") 
```
They do have the `UB` tag though. Is there a reason the UMI tag needs to be the uncorrected version? Would it be appropriate to set `--umi_tag` to `UB`?

Thank you!

**Comment by pfh** [comment]
Hi!

polyApipe.py uses umi_tools to count UMIs associated with peaks. This has its own UMI clustering method, so there is no need for corrected barcodes. However, I can't imagine there would be any harm using the corrected barcode. Using UB should be fine.
